language: generic
sudo: required
services:
    - docker
    

before_install:
    - docker build -t shubhzzz/react-test -f ./client/Dockerfile.dev ./client
    - docker build myotherproject

script:
    - docker run -e CI=true shubhzzz/react-test npm test

after_success: 
    - docker build -t shubhzzz/multi-client ./client
    - docker build -t shubhzzz/multi-server ./server
    - docker build -t shubhzzz/multi-nginx ./nginx
    - docker build -t shubhzzz/multi-worker ./worker

#log in to docker CLI
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
- docker push shubhzzz/multi-client
- docker push shubhzzz/multi-server
- docker push shubhzzz/multi-nginx
- docker push shubhzzz/multi-worker

